export const categoriesWithProducts: Record<string, string[]> = {
  Laptops: [
    "Select Product",
    "HP Chromebook 14 G1(ENERGY STAR)",
    "HP Chromebook 14 G1(ES)",
    "HP ENVY - 17t Touch Laptop",
    "HP ENVY x360 - 15t Laptop",
    "HP Pavilion 15t Touch Laptop",
    "HP Pavilion 15z Laptop",
    "HP Pavilion 15z Touch Laptop",
    "HP Pavilion x360 - 11t Touch Laptop",
    "HP Spectre x360 - 13-4102dx",
  ],
  Headphones: [
    "Select Product",
    "Beats Studio 2 Over-Ear Matte Black Headphones",
    "Bose SoundLink Around-ear Wireless Headphones II",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "game of thrones",
    "HP H2310 In-ear Headset",
    "Logitech USB Headset H390",
  ],
  Tablets: [
    "Select Product",
    "HP ElitePad 1000 G2 Tablet",
    "HP Elite x2 1011 G1 Tablet",
    "HP Pro Tablet 608 G1",
  ],
  Speakers: [
    "Select Product",
    "Bose Soundlink Bluetooth Speaker III",
    "Bose SoundLink Wireless Speaker",
    "HP Roar Mini Wireless Speaker",
    "HP Roar Plus Wireless Speaker",
    "HP Roar Wireless Speaker",
    "HP S9500 Bluetooth Wireless Speaker",
    "Logitech X100 Speaker System - Wireless Speaker(s)",
  ],
  Mice: [
    "Select Product",
    "HP USB 3 Button Optical Mouse",
    "HP Z3200 Wireless Mouse",
    "HP Z3600 Wireless Mouse",
    "HP Z4000 Wireless Mouse",
    "HP Z8000 Bluetooth Mouse",
    "Kensington Orbit 72337 Trackball with Scroll Ring",
    "Kensington Orbit 72352 Trackball",
    "Logitech G502 Proteus Core",
    "Microsoft Sculpt Touch Mouse",
  ],
};
